const MILISECONDS_PER_MINUTE = 1000 * 60;
const MILISECONDS_PER_HOUR = MILISECONDS_PER_MINUTE * 60;
const MILISECONDS_PER_DAY = MILISECONDS_PER_HOUR * 24;

export {MILISECONDS_PER_DAY, MILISECONDS_PER_HOUR, MILISECONDS_PER_MINUTE};
